notifications:
  email: false

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=csrg/generic_builder

install:
  - sudo docker pull $DOCKER_IMAGE

script:
  - sudo docker run --rm -v `pwd`:/workspace $DOCKER_IMAGE /workspace/travis/build-wheels.sh
